
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_FAILURE = 'SEND_PASSWORD_RESET_FAILURE';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const TENANT_LIST_REQUEST = 'TENANT_LIST_REQUEST';
export const TENANT_LIST_FAILURE = 'TENANT_LIST_FAILURE';
export const TENANT_LIST_SUCCESS = 'TENANT_LIST_SUCCESS';

export const TENANT_DETAIL_REQUEST = 'TENANT_DETAIL_REQUEST';
export const TENANT_DETAIL_FAILURE = 'TENANT_DETAIL_FAILURE';
export const TENANT_DETAIL_SUCCESS = 'TENANT_DETAIL_SUCCESS';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';

export const NAVIGATION_REQUEST = 'NAVIGATION_REQUEST';
export const NAVIGATION_FAILURE = 'NAVIGATION_FAILURE';
export const NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS';

export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_FAILURE = 'MEMBER_LIST_FAILURE';
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS';

export const MEMBER_DETAIL_REQUEST = 'MEMBER_DETAIL_REQUEST';
export const MEMBER_DETAIL_FAILURE = 'MEMBER_DETAIL_FAILURE';
export const MEMBER_DETAIL_SUCCESS = 'MEMBER_DETAIL_SUCCESS';
