
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

export const SEND_PASSWORD_RESET_REQUEST = 'SEND_PASSWORD_RESET_REQUEST';
export const SEND_PASSWORD_RESET_FAILURE = 'SEND_PASSWORD_RESET_FAILURE';
export const SEND_PASSWORD_RESET_SUCCESS = 'SEND_PASSWORD_RESET_SUCCESS';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

export const TENANT_LIST_REQUEST = 'TENANT_LIST_REQUEST';
export const TENANT_LIST_FAILURE = 'TENANT_LIST_FAILURE';
export const TENANT_LIST_SUCCESS = 'TENANT_LIST_SUCCESS';

export const TENANT_DETAIL_REQUEST = 'TENANT_DETAIL_REQUEST';
export const TENANT_DETAIL_FAILURE = 'TENANT_DETAIL_FAILURE';
export const TENANT_DETAIL_SUCCESS = 'TENANT_DETAIL_SUCCESS';

export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';

export const NAVIGATION_REQUEST = 'NAVIGATION_REQUEST';
export const NAVIGATION_FAILURE = 'NAVIGATION_FAILURE';
export const NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS';

export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST';
export const MEMBER_LIST_FAILURE = 'MEMBER_LIST_FAILURE';
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS';

export const MEMBER_DETAIL_REQUEST = 'MEMBER_DETAIL_REQUEST';
export const MEMBER_DETAIL_FAILURE = 'MEMBER_DETAIL_FAILURE';
export const MEMBER_DETAIL_SUCCESS = 'MEMBER_DETAIL_SUCCESS';

export const MEMBER_COMMENT_LIST_REQUEST = 'MEMBER_COMMENT_LIST_REQUEST';
export const MEMBER_COMMENT_LIST_FAILURE = 'MEMBER_COMMENT_LIST_FAILURE';
export const MEMBER_COMMENT_LIST_SUCCESS = 'MEMBER_COMMENT_LIST_SUCCESS';

export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST';
export const TAG_LIST_FAILURE = 'TAG_LIST_FAILURE';
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS';

export const TAG_DETAIL_REQUEST = 'TAG_DETAIL_REQUEST';
export const TAG_DETAIL_FAILURE = 'TAG_DETAIL_FAILURE';
export const TAG_DETAIL_SUCCESS = 'TAG_DETAIL_SUCCESS';

export const HOW_HEAR_LIST_REQUEST = 'HOW_HEAR_LIST_REQUEST';
export const HOW_HEAR_LIST_FAILURE = 'HOW_HEAR_LIST_FAILURE';
export const HOW_HEAR_LIST_SUCCESS = 'HOW_HEAR_LIST_SUCCESS';

export const HOW_HEAR_DETAIL_REQUEST = 'HOW_HEAR_DETAIL_REQUEST';
export const HOW_HEAR_DETAIL_FAILURE = 'HOW_HEAR_DETAIL_FAILURE';
export const HOW_HEAR_DETAIL_SUCCESS = 'HOW_HEAR_DETAIL_SUCCESS';

export const EXPECTATION_LIST_REQUEST = 'EXPECTATION_LIST_REQUEST';
export const EXPECTATION_LIST_FAILURE = 'EXPECTATION_LIST_FAILURE';
export const EXPECTATION_LIST_SUCCESS = 'EXPECTATION_LIST_SUCCESS';

export const EXPECTATION_DETAIL_REQUEST = 'EXPECTATION_DETAIL_REQUEST';
export const EXPECTATION_DETAIL_FAILURE = 'EXPECTATION_DETAIL_FAILURE';
export const EXPECTATION_DETAIL_SUCCESS = 'EXPECTATION_DETAIL_SUCCESS';

export const MEANING_LIST_REQUEST = 'MEANING_LIST_REQUEST';
export const MEANING_LIST_FAILURE = 'MEANING_LIST_FAILURE';
export const MEANING_LIST_SUCCESS = 'MEANING_LIST_SUCCESS';

export const MEANING_DETAIL_REQUEST = 'MEANING_DETAIL_REQUEST';
export const MEANING_DETAIL_FAILURE = 'MEANING_DETAIL_FAILURE';
export const MEANING_DETAIL_SUCCESS = 'MEANING_DETAIL_SUCCESS';

export const PRIVATE_FILE_UPLOAD_LIST_REQUEST = 'PRIVATE_FILE_UPLOAD_LIST_REQUEST';
export const PRIVATE_FILE_UPLOAD_LIST_FAILURE = 'PRIVATE_FILE_UPLOAD_LIST_FAILURE';
export const PRIVATE_FILE_UPLOAD_LIST_SUCCESS = 'PRIVATE_FILE_UPLOAD_LIST_SUCCESS';

export const AREA_COORDINATOR_LIST_REQUEST = 'AREA_COORDINATOR_LIST_REQUEST';
export const AREA_COORDINATOR_LIST_FAILURE = 'AREA_COORDINATOR_LIST_FAILURE';
export const AREA_COORDINATOR_LIST_SUCCESS = 'AREA_COORDINATOR_LIST_SUCCESS';

export const AREA_COORDINATOR_DETAIL_REQUEST = 'AREA_COORDINATOR_DETAIL_REQUEST';
export const AREA_COORDINATOR_DETAIL_FAILURE = 'AREA_COORDINATOR_DETAIL_FAILURE';
export const AREA_COORDINATOR_DETAIL_SUCCESS = 'AREA_COORDINATOR_DETAIL_SUCCESS';

export const AREA_COORDINATOR_COMMENT_LIST_REQUEST = 'AREA_COORDINATOR_COMMENT_LIST_REQUEST';
export const AREA_COORDINATOR_COMMENT_LIST_FAILURE = 'AREA_COORDINATOR_COMMENT_LIST_FAILURE';
export const AREA_COORDINATOR_COMMENT_LIST_SUCCESS = 'AREA_COORDINATOR_COMMENT_LIST_SUCCESS';

export const ASSOCIATE_LIST_REQUEST = 'ASSOCIATE_LIST_REQUEST';
export const ASSOCIATE_LIST_FAILURE = 'ASSOCIATE_LIST_FAILURE';
export const ASSOCIATE_LIST_SUCCESS = 'ASSOCIATE_LIST_SUCCESS';

export const ASSOCIATE_DETAIL_REQUEST = 'ASSOCIATE_DETAIL_REQUEST';
export const ASSOCIATE_DETAIL_FAILURE = 'ASSOCIATE_DETAIL_FAILURE';
export const ASSOCIATE_DETAIL_SUCCESS = 'ASSOCIATE_DETAIL_SUCCESS';

export const ASSOCIATE_COMMENT_LIST_REQUEST = 'ASSOCIATE_COMMENT_LIST_REQUEST';
export const ASSOCIATE_COMMENT_LIST_FAILURE = 'ASSOCIATE_COMMENT_LIST_FAILURE';
export const ASSOCIATE_COMMENT_LIST_SUCCESS = 'ASSOCIATE_COMMENT_LIST_SUCCESS';

export const SCORE_POINT_LIST_REQUEST = 'SCORE_POINT_LIST_REQUEST';
export const SCORE_POINT_LIST_FAILURE = 'SCORE_POINT_LIST_FAILURE';
export const SCORE_POINT_LIST_SUCCESS = 'SCORE_POINT_LIST_SUCCESS';

export const SCORE_POINT_DETAIL_REQUEST = 'SCORE_POINT_DETAIL_REQUEST';
export const SCORE_POINT_DETAIL_FAILURE = 'SCORE_POINT_DETAIL_FAILURE';
export const SCORE_POINT_DETAIL_SUCCESS = 'SCORE_POINT_DETAIL_SUCCESS';

export const BADGE_LIST_REQUEST = 'BADGE_LIST_REQUEST';
export const BADGE_LIST_FAILURE = 'BADGE_LIST_FAILURE';
export const BADGE_LIST_SUCCESS = 'BADGE_LIST_SUCCESS';

export const BADGE_DETAIL_REQUEST = 'BADGE_DETAIL_REQUEST';
export const BADGE_DETAIL_FAILURE = 'BADGE_DETAIL_FAILURE';
export const BADGE_DETAIL_SUCCESS = 'BADGE_DETAIL_SUCCESS';

export const AWARD_LIST_REQUEST = 'AWARD_LIST_REQUEST';
export const AWARD_LIST_FAILURE = 'AWARD_LIST_FAILURE';
export const AWARD_LIST_SUCCESS = 'AWARD_LIST_SUCCESS';

export const AWARD_DETAIL_REQUEST = 'AWARD_DETAIL_REQUEST';
export const AWARD_DETAIL_FAILURE = 'AWARD_DETAIL_FAILURE';
export const AWARD_DETAIL_SUCCESS = 'AWARD_DETAIL_SUCCESS';
